//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiapWebServices_Library.EleClienti_WSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servizi.Anagrafiche.APWebServices", ConfigurationName="EleClienti_WSService.EleClienti_WS")]
    public interface EleClienti_WS {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructAnaCliente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ricercaReturn")]
        SiapWebServices_Library.EleClienti_WSService.StructRicClientiOut ricerca(SiapWebServices_Library.EleClienti_WSService.StructRicClientiIn structIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ricercaReturn")]
        System.Threading.Tasks.Task<SiapWebServices_Library.EleClienti_WSService.StructRicClientiOut> ricercaAsync(SiapWebServices_Library.EleClienti_WSService.StructRicClientiIn structIn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://Strutture.Anagrafiche.APWebServices")]
    public partial class StructRicClientiIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StructLogin iLoginField;
        
        private StructParamRicCliIn paramRicCliInField;
        
        private string tipoRicercaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public StructLogin ILogin {
            get {
                return this.iLoginField;
            }
            set {
                this.iLoginField = value;
                this.RaisePropertyChanged("ILogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public StructParamRicCliIn paramRicCliIn {
            get {
                return this.paramRicCliInField;
            }
            set {
                this.paramRicCliInField = value;
                this.RaisePropertyChanged("paramRicCliIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoRicerca {
            get {
                return this.tipoRicercaField;
            }
            set {
                this.tipoRicercaField = value;
                this.RaisePropertyChanged("tipoRicerca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://Strutture.WebServices.siap.com")]
    public partial class StructLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string utenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string utente {
            get {
                return this.utenteField;
            }
            set {
                this.utenteField = value;
                this.RaisePropertyChanged("utente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://Strutture.WebServices.siap.com")]
    public partial class StructEsito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messaggioField;
        
        private string statoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string messaggio {
            get {
                return this.messaggioField;
            }
            set {
                this.messaggioField = value;
                this.RaisePropertyChanged("messaggio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                this.statoField = value;
                this.RaisePropertyChanged("stato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://Strutture.Anagrafiche.APWebServices")]
    public partial class StructAnaCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ammessoCreditoField;
        
        private string annullamentoField;
        
        private string capField;
        
        private string categoriaClienteField;
        
        private string checkDigitField;
        
        private string cinField;
        
        private string codAgenteField;
        
        private string codBancaField;
        
        private string codClienteAltroSistemaField;
        
        private string codDivisaField;
        
        private string codGruppoField;
        
        private string codIVAField;
        
        private string codNazCodFiscaleField;
        
        private string codNsBancaField;
        
        private string codProfessioneField;
        
        private string codTitoloField;
        
        private string codiceFiscaleField;
        
        private string codiceNazioneField;
        
        private string cognomeField;
        
        private string consensoPrivacyField;
        
        private string consensoPubblicitaField;
        
        private string consensoPubblicitaElettrField;
        
        private string consensoPubblicitaTerziField;
        
        private string contoCliente12Field;
        
        private string contocorrenteBancarioField;
        
        private string cpdc_personalizzatoField;
        
        private string dataAttivazCartaGlobeTrotterField;
        
        private string dataConsensoField;
        
        private string dataGaranziaRIDField;
        
        private string dataNascitaField;
        
        private string dataRilascioDocField;
        
        private string dataScadDocField;
        
        private string emailField;
        
        private string enteRilascioDocField;
        
        private string idMimixField;
        
        private string indirSpedRIBAField;
        
        private string indirizzoField;
        
        private string invioDocEmailField;
        
        private string locNascitaField;
        
        private string locRilascioDocField;
        
        private string localitaField;
        
        private string modPagamentoField;
        
        private string nomeField;
        
        private string numeroCartaGlobeTrotterField;
        
        private string numeroCellulareField;
        
        private string numeroDocumentoField;
        
        private string numeroFaxField;
        
        private string numeroTel1Field;
        
        private string numeroTel2Field;
        
        private string numeroTel3Field;
        
        private string partitaIvaField;
        
        private string persFisicaGiurField;
        
        private string prefissoInternazField;
        
        private string provNascitaField;
        
        private string provRilascioDocField;
        
        private string provinciaField;
        
        private string ragioneSocInRichiestaField;
        
        private string ragioneSocialeField;
        
        private string sessoField;
        
        private string tipoDocumentoField;
        
        private string tipologiaClienteField;
        
        private string unitaOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ammessoCredito {
            get {
                return this.ammessoCreditoField;
            }
            set {
                this.ammessoCreditoField = value;
                this.RaisePropertyChanged("ammessoCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string annullamento {
            get {
                return this.annullamentoField;
            }
            set {
                this.annullamentoField = value;
                this.RaisePropertyChanged("annullamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string categoriaCliente {
            get {
                return this.categoriaClienteField;
            }
            set {
                this.categoriaClienteField = value;
                this.RaisePropertyChanged("categoriaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string checkDigit {
            get {
                return this.checkDigitField;
            }
            set {
                this.checkDigitField = value;
                this.RaisePropertyChanged("checkDigit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cin {
            get {
                return this.cinField;
            }
            set {
                this.cinField = value;
                this.RaisePropertyChanged("cin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codAgente {
            get {
                return this.codAgenteField;
            }
            set {
                this.codAgenteField = value;
                this.RaisePropertyChanged("codAgente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codBanca {
            get {
                return this.codBancaField;
            }
            set {
                this.codBancaField = value;
                this.RaisePropertyChanged("codBanca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codClienteAltroSistema {
            get {
                return this.codClienteAltroSistemaField;
            }
            set {
                this.codClienteAltroSistemaField = value;
                this.RaisePropertyChanged("codClienteAltroSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codDivisa {
            get {
                return this.codDivisaField;
            }
            set {
                this.codDivisaField = value;
                this.RaisePropertyChanged("codDivisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codGruppo {
            get {
                return this.codGruppoField;
            }
            set {
                this.codGruppoField = value;
                this.RaisePropertyChanged("codGruppo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codIVA {
            get {
                return this.codIVAField;
            }
            set {
                this.codIVAField = value;
                this.RaisePropertyChanged("codIVA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codNazCodFiscale {
            get {
                return this.codNazCodFiscaleField;
            }
            set {
                this.codNazCodFiscaleField = value;
                this.RaisePropertyChanged("codNazCodFiscale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codNsBanca {
            get {
                return this.codNsBancaField;
            }
            set {
                this.codNsBancaField = value;
                this.RaisePropertyChanged("codNsBanca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codProfessione {
            get {
                return this.codProfessioneField;
            }
            set {
                this.codProfessioneField = value;
                this.RaisePropertyChanged("codProfessione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codTitolo {
            get {
                return this.codTitoloField;
            }
            set {
                this.codTitoloField = value;
                this.RaisePropertyChanged("codTitolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceFiscale {
            get {
                return this.codiceFiscaleField;
            }
            set {
                this.codiceFiscaleField = value;
                this.RaisePropertyChanged("codiceFiscale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceNazione {
            get {
                return this.codiceNazioneField;
            }
            set {
                this.codiceNazioneField = value;
                this.RaisePropertyChanged("codiceNazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
                this.RaisePropertyChanged("cognome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string consensoPrivacy {
            get {
                return this.consensoPrivacyField;
            }
            set {
                this.consensoPrivacyField = value;
                this.RaisePropertyChanged("consensoPrivacy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string consensoPubblicita {
            get {
                return this.consensoPubblicitaField;
            }
            set {
                this.consensoPubblicitaField = value;
                this.RaisePropertyChanged("consensoPubblicita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string consensoPubblicitaElettr {
            get {
                return this.consensoPubblicitaElettrField;
            }
            set {
                this.consensoPubblicitaElettrField = value;
                this.RaisePropertyChanged("consensoPubblicitaElettr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string consensoPubblicitaTerzi {
            get {
                return this.consensoPubblicitaTerziField;
            }
            set {
                this.consensoPubblicitaTerziField = value;
                this.RaisePropertyChanged("consensoPubblicitaTerzi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contoCliente12 {
            get {
                return this.contoCliente12Field;
            }
            set {
                this.contoCliente12Field = value;
                this.RaisePropertyChanged("contoCliente12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contocorrenteBancario {
            get {
                return this.contocorrenteBancarioField;
            }
            set {
                this.contocorrenteBancarioField = value;
                this.RaisePropertyChanged("contocorrenteBancario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cpdc_personalizzato {
            get {
                return this.cpdc_personalizzatoField;
            }
            set {
                this.cpdc_personalizzatoField = value;
                this.RaisePropertyChanged("cpdc_personalizzato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataAttivazCartaGlobeTrotter {
            get {
                return this.dataAttivazCartaGlobeTrotterField;
            }
            set {
                this.dataAttivazCartaGlobeTrotterField = value;
                this.RaisePropertyChanged("dataAttivazCartaGlobeTrotter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataConsenso {
            get {
                return this.dataConsensoField;
            }
            set {
                this.dataConsensoField = value;
                this.RaisePropertyChanged("dataConsenso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataGaranziaRID {
            get {
                return this.dataGaranziaRIDField;
            }
            set {
                this.dataGaranziaRIDField = value;
                this.RaisePropertyChanged("dataGaranziaRID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataNascita {
            get {
                return this.dataNascitaField;
            }
            set {
                this.dataNascitaField = value;
                this.RaisePropertyChanged("dataNascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataRilascioDoc {
            get {
                return this.dataRilascioDocField;
            }
            set {
                this.dataRilascioDocField = value;
                this.RaisePropertyChanged("dataRilascioDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataScadDoc {
            get {
                return this.dataScadDocField;
            }
            set {
                this.dataScadDocField = value;
                this.RaisePropertyChanged("dataScadDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string enteRilascioDoc {
            get {
                return this.enteRilascioDocField;
            }
            set {
                this.enteRilascioDocField = value;
                this.RaisePropertyChanged("enteRilascioDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string idMimix {
            get {
                return this.idMimixField;
            }
            set {
                this.idMimixField = value;
                this.RaisePropertyChanged("idMimix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string indirSpedRIBA {
            get {
                return this.indirSpedRIBAField;
            }
            set {
                this.indirSpedRIBAField = value;
                this.RaisePropertyChanged("indirSpedRIBA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string invioDocEmail {
            get {
                return this.invioDocEmailField;
            }
            set {
                this.invioDocEmailField = value;
                this.RaisePropertyChanged("invioDocEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string locNascita {
            get {
                return this.locNascitaField;
            }
            set {
                this.locNascitaField = value;
                this.RaisePropertyChanged("locNascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string locRilascioDoc {
            get {
                return this.locRilascioDocField;
            }
            set {
                this.locRilascioDocField = value;
                this.RaisePropertyChanged("locRilascioDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modPagamento {
            get {
                return this.modPagamentoField;
            }
            set {
                this.modPagamentoField = value;
                this.RaisePropertyChanged("modPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroCartaGlobeTrotter {
            get {
                return this.numeroCartaGlobeTrotterField;
            }
            set {
                this.numeroCartaGlobeTrotterField = value;
                this.RaisePropertyChanged("numeroCartaGlobeTrotter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroCellulare {
            get {
                return this.numeroCellulareField;
            }
            set {
                this.numeroCellulareField = value;
                this.RaisePropertyChanged("numeroCellulare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroFax {
            get {
                return this.numeroFaxField;
            }
            set {
                this.numeroFaxField = value;
                this.RaisePropertyChanged("numeroFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroTel1 {
            get {
                return this.numeroTel1Field;
            }
            set {
                this.numeroTel1Field = value;
                this.RaisePropertyChanged("numeroTel1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroTel2 {
            get {
                return this.numeroTel2Field;
            }
            set {
                this.numeroTel2Field = value;
                this.RaisePropertyChanged("numeroTel2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroTel3 {
            get {
                return this.numeroTel3Field;
            }
            set {
                this.numeroTel3Field = value;
                this.RaisePropertyChanged("numeroTel3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string partitaIva {
            get {
                return this.partitaIvaField;
            }
            set {
                this.partitaIvaField = value;
                this.RaisePropertyChanged("partitaIva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string persFisicaGiur {
            get {
                return this.persFisicaGiurField;
            }
            set {
                this.persFisicaGiurField = value;
                this.RaisePropertyChanged("persFisicaGiur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string prefissoInternaz {
            get {
                return this.prefissoInternazField;
            }
            set {
                this.prefissoInternazField = value;
                this.RaisePropertyChanged("prefissoInternaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string provNascita {
            get {
                return this.provNascitaField;
            }
            set {
                this.provNascitaField = value;
                this.RaisePropertyChanged("provNascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string provRilascioDoc {
            get {
                return this.provRilascioDocField;
            }
            set {
                this.provRilascioDocField = value;
                this.RaisePropertyChanged("provRilascioDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ragioneSocInRichiesta {
            get {
                return this.ragioneSocInRichiestaField;
            }
            set {
                this.ragioneSocInRichiestaField = value;
                this.RaisePropertyChanged("ragioneSocInRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ragioneSociale {
            get {
                return this.ragioneSocialeField;
            }
            set {
                this.ragioneSocialeField = value;
                this.RaisePropertyChanged("ragioneSociale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sesso {
            get {
                return this.sessoField;
            }
            set {
                this.sessoField = value;
                this.RaisePropertyChanged("sesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipologiaCliente {
            get {
                return this.tipologiaClienteField;
            }
            set {
                this.tipologiaClienteField = value;
                this.RaisePropertyChanged("tipologiaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unitaOp {
            get {
                return this.unitaOpField;
            }
            set {
                this.unitaOpField = value;
                this.RaisePropertyChanged("unitaOp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://Strutture.Anagrafiche.APWebServices")]
    public partial class StructRicClientiOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string azioneEseguitaField;
        
        private StructAnaCliente[] eleClientiField;
        
        private StructEsito esitoField;
        
        private string risultatoCompletoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string azioneEseguita {
            get {
                return this.azioneEseguitaField;
            }
            set {
                this.azioneEseguitaField = value;
                this.RaisePropertyChanged("azioneEseguita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public StructAnaCliente[] eleClienti {
            get {
                return this.eleClientiField;
            }
            set {
                this.eleClientiField = value;
                this.RaisePropertyChanged("eleClienti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public StructEsito esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("esito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string risultatoCompleto {
            get {
                return this.risultatoCompletoField;
            }
            set {
                this.risultatoCompletoField = value;
                this.RaisePropertyChanged("risultatoCompleto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://Strutture.Anagrafiche.APWebServices")]
    public partial class StructParamRicCliIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codCliente12Field;
        
        private string codNazioneField;
        
        private string codRegioneField;
        
        private string codZonaField;
        
        private string codiceFiscaleField;
        
        private string dataUltimaModificaField;
        
        private string localitaField;
        
        private string numeroTelField;
        
        private string partitaIvaField;
        
        private string ragioneSocialeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codCliente12 {
            get {
                return this.codCliente12Field;
            }
            set {
                this.codCliente12Field = value;
                this.RaisePropertyChanged("codCliente12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codNazione {
            get {
                return this.codNazioneField;
            }
            set {
                this.codNazioneField = value;
                this.RaisePropertyChanged("codNazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codRegione {
            get {
                return this.codRegioneField;
            }
            set {
                this.codRegioneField = value;
                this.RaisePropertyChanged("codRegione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codZona {
            get {
                return this.codZonaField;
            }
            set {
                this.codZonaField = value;
                this.RaisePropertyChanged("codZona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceFiscale {
            get {
                return this.codiceFiscaleField;
            }
            set {
                this.codiceFiscaleField = value;
                this.RaisePropertyChanged("codiceFiscale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataUltimaModifica {
            get {
                return this.dataUltimaModificaField;
            }
            set {
                this.dataUltimaModificaField = value;
                this.RaisePropertyChanged("dataUltimaModifica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroTel {
            get {
                return this.numeroTelField;
            }
            set {
                this.numeroTelField = value;
                this.RaisePropertyChanged("numeroTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string partitaIva {
            get {
                return this.partitaIvaField;
            }
            set {
                this.partitaIvaField = value;
                this.RaisePropertyChanged("partitaIva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ragioneSociale {
            get {
                return this.ragioneSocialeField;
            }
            set {
                this.ragioneSocialeField = value;
                this.RaisePropertyChanged("ragioneSociale");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EleClienti_WSChannel : SiapWebServices_Library.EleClienti_WSService.EleClienti_WS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EleClienti_WSClient : System.ServiceModel.ClientBase<SiapWebServices_Library.EleClienti_WSService.EleClienti_WS>, SiapWebServices_Library.EleClienti_WSService.EleClienti_WS {
        
        public EleClienti_WSClient() {
        }
        
        public EleClienti_WSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EleClienti_WSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EleClienti_WSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EleClienti_WSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiapWebServices_Library.EleClienti_WSService.StructRicClientiOut ricerca(SiapWebServices_Library.EleClienti_WSService.StructRicClientiIn structIn) {
            return base.Channel.ricerca(structIn);
        }
        
        public System.Threading.Tasks.Task<SiapWebServices_Library.EleClienti_WSService.StructRicClientiOut> ricercaAsync(SiapWebServices_Library.EleClienti_WSService.StructRicClientiIn structIn) {
            return base.Channel.ricercaAsync(structIn);
        }
    }
}
